# Python Exercises: Part 1 (numpy, scipy, matplotlib)

## Goal:
- Understand purpose and general methodology of $\texttt{numpy}$, $\texttt{scipy}$, and $\texttt{matplotlib}$

## Imports
- for an installed package, specify which components (objects, methods, etc.)
- give appropriate name (e.g. np = numpy)
- "." steps one layer beneath (e.g. matplotlib.pyplot)

In [1]:
import numpy as np # convention
import matplotlib.pyplot as plt # convention

## Package #1: $\texttt{numpy}$

- Primary contribution: **numpy.array** data structure
    - similar to lists in structure (for 1D array)
    - allows for vectorized calculations
    
- Similar to Matlab

### Simple Example: Bitwise Addition

#### numpy:

In [13]:
# initialize numpy arrays
a = np.array([1,2,3])
b = np.array([4,5,6])

In [11]:
# add
a + b

array([5, 7, 9])

In [12]:
# add using numpy method np.add
np.add(a,b)

array([5, 7, 9])

In [14]:
# how long does it take?
%timeit a + b

406 ns ± 7.64 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### python lists:

In [15]:
a = [1,2,3]
b = [4,5,6]

In [16]:
# + operator
a + b

[1, 2, 3, 4, 5, 6]

This just concatenates lists, but we wanted to add element by element.

In [17]:
def list_add(x, y):
    result = []
    for xx,yy in zip(x,y):
        result.append(xx+yy)
    
    return result

In [18]:
list_add(a,b)

[5, 7, 9]

In [19]:
# how long does it take?
%timeit list_add(a, b)

466 ns ± 8.08 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


So, why use numpy?
- easier
- optimized to run quickly
- in general, vectorized calculations are more efficient!
    - vectorized means do many of the same calculations (e.g. addition) on all elements at the same time
- allows introduction to linear algebra concepts

In [25]:
# 10,000 random integers plus 10,000 random integers
a_np = np.random.randint(low=0, high=100, size=10000)
b_np = np.random.randint(low=0, high=100, size=10000)

In [26]:
a_np

array([28, 47, 71, ..., 22, 27, 74])

In [28]:
a_np + b_np

array([ 97, 131, 163, ...,  67,  38, 159])

In [29]:
%timeit a_np + b_np

4.07 µs ± 22.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [32]:
a_list = list(a_np)
b_list = list(b_np)

In [33]:
#list_add(a_list, b_list)

[97,
 131,
 163,
 182,
 23,
 110,
 84,
 122,
 122,
 64,
 192,
 104,
 149,
 101,
 48,
 89,
 138,
 123,
 82,
 53,
 72,
 38,
 7,
 73,
 94,
 180,
 68,
 90,
 57,
 23,
 114,
 106,
 74,
 99,
 23,
 67,
 140,
 81,
 124,
 95,
 169,
 160,
 63,
 102,
 146,
 158,
 77,
 78,
 24,
 91,
 140,
 100,
 21,
 136,
 146,
 123,
 110,
 101,
 177,
 174,
 22,
 100,
 63,
 128,
 47,
 64,
 49,
 141,
 105,
 55,
 163,
 91,
 140,
 180,
 182,
 92,
 80,
 75,
 116,
 35,
 139,
 56,
 112,
 73,
 122,
 45,
 133,
 35,
 35,
 107,
 45,
 28,
 129,
 68,
 52,
 159,
 108,
 54,
 193,
 86,
 86,
 88,
 76,
 71,
 46,
 141,
 125,
 131,
 78,
 82,
 44,
 56,
 159,
 81,
 116,
 88,
 128,
 150,
 136,
 54,
 19,
 55,
 70,
 147,
 64,
 40,
 132,
 29,
 103,
 86,
 92,
 102,
 108,
 140,
 95,
 144,
 88,
 61,
 66,
 56,
 79,
 131,
 178,
 44,
 91,
 73,
 76,
 172,
 107,
 109,
 154,
 124,
 25,
 78,
 149,
 101,
 92,
 57,
 87,
 100,
 162,
 122,
 120,
 22,
 187,
 147,
 59,
 85,
 83,
 93,
 140,
 50,
 184,
 62,
 140,
 107,
 108,
 88,
 117,
 100,
 131,
 127,
 67

In [34]:
%timeit list_add(a_list, b_list)

1.05 ms ± 9.62 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


For a vector with 10,000 elements, numpy is ~250x faster for something simple like addition! **This makes a big difference when doing more complex operations or big calculations**